#!/usr/bin/env python3
"""Pack photos into flash-efficient 128x160 indexed images for Slideshow.

Each source image is centre-cropped to the display aspect ratio, resized to
128x160, quantized to its own 16-colour palette, and packed as 4-bit indices.
One converted frame consumes 10,240 bytes of flash rather than 40,960 bytes of
RGB565 data. The generated header is consumed directly by src/main.c.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

try:
    from PIL import Image
except ImportError as error:
    raise SystemExit("Pillow is required. Install it with: py -m pip install pillow") from error


WIDTH = 128
HEIGHT = 160
PALETTE_SIZE = 16
DEFAULT_MAX_IMAGES = 3
SUPPORTED_SUFFIXES = {".bmp", ".gif", ".jpeg", ".jpg", ".png", ".webp"}


def parse_args() -> argparse.Namespace:
    project_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=project_dir.parent / "photos",
                        help="folder containing source photos (default: examples/photos)")
    parser.add_argument("--output", type=Path, default=project_dir / "generated" / "photos.h",
                        help="generated C header path (default: generated/photos.h)")
    parser.add_argument("--max-images", type=int, default=DEFAULT_MAX_IMAGES,
                        help="maximum number of photos to embed (default: 3)")
    return parser.parse_args()


def list_images(directory: Path) -> list[Path]:
    if not directory.is_dir():
        raise SystemExit(f"Photo folder does not exist: {directory}")
    images = sorted(
        (path for path in directory.iterdir()
         if path.is_file() and path.suffix.lower() in SUPPORTED_SUFFIXES),
        key=lambda path: path.name.casefold(),
    )
    if not images:
        extensions = ", ".join(sorted(SUPPORTED_SUFFIXES))
        raise SystemExit(f"No supported image files in {directory} ({extensions})")
    return images


def crop_to_display(image: Image.Image) -> Image.Image:
    """Return an RGB image centre-cropped to 4:5, then resized for the LCD."""
    image = image.convert("RGB")
    source_width, source_height = image.size
    if source_width <= 0 or source_height <= 0:
        raise ValueError("image has an invalid size")

    target_ratio = WIDTH / HEIGHT
    source_ratio = source_width / source_height
    if source_ratio > target_ratio:
        crop_width = int(source_height * target_ratio)
        left = (source_width - crop_width) // 2
        image = image.crop((left, 0, left + crop_width, source_height))
    elif source_ratio < target_ratio:
        crop_height = int(source_width / target_ratio)
        top = (source_height - crop_height) // 2
        image = image.crop((0, top, source_width, top + crop_height))

    return image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)


def rgb_to_panel_rgb565(red: int, green: int, blue: int) -> int:
    """Match display.h's COL_RGB: panel MADCTL requires BGR-swapped RGB565."""
    return ((blue >> 3) << 11) | ((green >> 2) << 5) | (red >> 3)


def pack_image(path: Path) -> tuple[list[int], bytes]:
    with Image.open(path) as source:
        resized = crop_to_display(source)
        quantized = resized.quantize(colors=PALETTE_SIZE, method=Image.Quantize.MEDIANCUT)

    palette_data = quantized.getpalette() or []
    palette: list[int] = []
    for index in range(PALETTE_SIZE):
        base = index * 3
        red, green, blue = palette_data[base : base + 3]
        palette.append(rgb_to_panel_rgb565(red, green, blue))

    indices = list(quantized.getdata())
    if len(indices) != WIDTH * HEIGHT:
        raise ValueError(f"unexpected converted size for {path}")

    packed = bytearray()
    for offset in range(0, len(indices), 2):
        packed.append((indices[offset] << 4) | indices[offset + 1])
    return palette, bytes(packed)


def c_bytes(data: Iterable[int], indent: str = "    ", per_line: int = 12) -> str:
    values = list(data)
    lines: list[str] = []
    for offset in range(0, len(values), per_line):
        row = ", ".join(f"0x{value:02X}" for value in values[offset : offset + per_line])
        lines.append(f"{indent}{row},")
    return "\n".join(lines)


def write_header(output: Path, frames: list[tuple[Path, list[int], bytes]]) -> None:
    lines = [
        "/* Generated by convert_images.py. Do not edit; rebuild from examples/photos. */",
        "#ifndef SLIDESHOW_PHOTOS_H",
        "#define SLIDESHOW_PHOTOS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define SLIDESHOW_IMAGE_COUNT {len(frames)}u",
        f"#define SLIDESHOW_IMAGE_WIDTH {WIDTH}u",
        f"#define SLIDESHOW_IMAGE_HEIGHT {HEIGHT}u",
        "",
        "typedef struct {",
        "    const uint16_t *palette;",
        "    const uint8_t *pixels;",
        "} slideshow_image_t;",
        "",
    ]
    for index, (source, palette, pixels) in enumerate(frames):
        lines.extend([
            f"/* {source.name}: {WIDTH}x{HEIGHT}, 16 colours, 4 bits/pixel. */",
            f"static const uint16_t g_slide_palette_{index}[{PALETTE_SIZE}] = {{",
            "    " + ", ".join(f"0x{colour:04X}" for colour in palette) + ",",
            "};",
            f"static const uint8_t g_slide_pixels_{index}[{len(pixels)}] = {{",
            c_bytes(pixels),
            "};",
            "",
        ])

    lines.append("static const slideshow_image_t g_slides[SLIDESHOW_IMAGE_COUNT] = {")
    for index, _frame in enumerate(frames):
        lines.append(f"    {{ g_slide_palette_{index}, g_slide_pixels_{index} }},")
    lines.extend(["};", "", "#endif /* SLIDESHOW_PHOTOS_H */", ""])

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    args = parse_args()
    if args.max_images < 1:
        raise SystemExit("--max-images must be at least 1")

    images = list_images(args.input)
    if len(images) > args.max_images:
        raise SystemExit(
            f"Found {len(images)} photos, but the firmware limit is {args.max_images}. "
            "Remove photos or pass a deliberately larger --max-images value after checking flash usage."
        )

    frames: list[tuple[Path, list[int], bytes]] = []
    for path in images:
        try:
            palette, pixels = pack_image(path)
        except (OSError, ValueError) as error:
            raise SystemExit(f"Cannot convert {path}: {error}") from error
        frames.append((path, palette, pixels))

    write_header(args.output, frames)
    asset_bytes = sum(len(pixels) + PALETTE_SIZE * 2 for _path, _palette, pixels in frames)
    print(f"Wrote {args.output} with {len(frames)} photo(s), {asset_bytes:,} bytes of image data.")


if __name__ == "__main__":
    main()
