#!/usr/bin/env python3
"""Generate an OpenOCD script that writes build/slideshow.bin directly to flash."""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


FLASH_BASE = 0x08000000
FLASH_PAGE_SIZE = 512
FLASH_APP_SIZE = 60 * 1024  # Top 4 KB is reserved for the SDK NV store.
IWDG_KR = 0x40003000
FLASH_KEYR = 0x40022004
FLASH_SR = 0x4002200C
FLASH_CR = 0x40022010
FLASH_AR = 0x40022014


def parse_args() -> argparse.Namespace:
    directory = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("binary", nargs="?", type=Path, default=directory / "build" / "slideshow.bin")
    parser.add_argument("output", nargs="?", type=Path, default=directory / "direct_flash.tcl")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.binary.is_file():
        raise SystemExit(f"Firmware binary not found: {args.binary}. Run build_slideshow.bat first.")

    data = args.binary.read_bytes()
    if not data:
        raise SystemExit("Firmware binary is empty.")
    data += b"\xff" * ((-len(data)) % 4)
    if len(data) > FLASH_APP_SIZE:
        raise SystemExit(
            f"Firmware is {len(data):,} bytes, exceeding the 60 KB application region. "
            "Refusing to erase the 4 KB NV store."
        )
    words = struct.unpack(f"<{len(data) // 4}I", data)
    page_count = (len(data) + FLASH_PAGE_SIZE - 1) // FLASH_PAGE_SIZE
    verify_path = f"/tmp/{args.binary.stem}_verify.bin"

    lines = [
        "# Generated by gen_direct_flash.py. Do not edit.",
        f"# Source: {args.binary.name}; {len(data)} bytes, {page_count} pages.",
        "init",
        "adapter speed 1000",
        "catch {halt}",
        "sleep 20",
        "catch {halt}",
        "sleep 20",
        "# Extend the active watchdog so erase/program operations have time to complete.",
        f"mww 0x{IWDG_KR:08X} 0x0000AAAA",
        f"mww 0x{IWDG_KR:08X} 0x00005555",
        "mww 0x40003004 0x00000006",
        "mww 0x40003008 0x00000FFF",
        f"mww 0x{IWDG_KR:08X} 0x0000AAAA",
        f"mww 0x{FLASH_KEYR:08X} 0x45670123",
        f"mww 0x{FLASH_KEYR:08X} 0xCDEF89AB",
        f"mww 0x{FLASH_SR:08X} 0x00000034",
        "",
        "# Erase only the pages occupied by the image. The final 4 KB NV area is untouched.",
    ]

    for page in range(page_count):
        address = FLASH_BASE + page * FLASH_PAGE_SIZE
        lines.extend([
            f"mww 0x{IWDG_KR:08X} 0x0000AAAA",
            f"puts \"Erasing 0x{address:08X}\"",
            f"mww 0x{FLASH_AR:08X} 0x{address:08X}",
            f"mww 0x{FLASH_CR:08X} 0x00000002",
            f"mww 0x{FLASH_CR:08X} 0x00000042",
            "sleep 30",
            f"mww 0x{FLASH_CR:08X} 0x00000000",
            f"mww 0x{FLASH_SR:08X} 0x00000034",
        ])

    lines.extend(["", "# Program words; feed IWDG regularly during the transfer.", f"mww 0x{FLASH_CR:08X} 0x00000001"])
    for index, word in enumerate(words):
        if index % 30 == 0:
            lines.append(f"mww 0x{IWDG_KR:08X} 0x0000AAAA")
        lines.append(f"mww 0x{FLASH_BASE + index * 4:08X} 0x{word:08X}")

    first_word = words[0]
    lines.extend([
        f"mww 0x{FLASH_CR:08X} 0x00000000",
        f"set first [mrw 0x{FLASH_BASE:08X}]",
        f"puts \"First programmed word: 0x[format %08X $first] (expect 0x{first_word:08X})\"",
        f"dump_image {verify_path} 0x{FLASH_BASE:08X} {len(data)}",
        f"puts \"Verification dump: {verify_path}\"",
        f"mww 0x{IWDG_KR:08X} 0x0000AAAA",
        "reset run",
        "sleep 200",
        "shutdown",
        "",
    ])
    args.output.write_text("\n".join(lines), encoding="ascii")
    print(f"Generated {args.output} for {len(data):,} bytes ({page_count} page(s)).")


if __name__ == "__main__":
    main()
