#!/usr/bin/env python3
"""Generate direct_flash.tcl — writes flappy.bin to flash word-by-word via PG mode."""
import struct, sys, os

bin_path = os.path.join(os.path.dirname(__file__), "build", "flappy.bin")
out_path = os.path.join(os.path.dirname(__file__), "direct_flash.tcl")

with open(bin_path, "rb") as f:
    data = f.read()

# Pad to word boundary
while len(data) % 4:
    data += b'\xff'

words = struct.unpack_from('<' + 'I' * (len(data) // 4), data)
nwords = len(words)
nbytes = len(data)
flash_base = 0x08000000

lines = []
lines.append("# direct_flash.tcl — generated by gen_direct_flash.py")
lines.append("# Writes flappy.bin ({} bytes, {} words) directly to flash via PG mode".format(nbytes, nwords))
lines.append("")
lines.append("init")
lines.append("adapter speed 1000")
lines.append("")
lines.append("# === HALT (robust) ===")
lines.append("catch {halt}")
lines.append("sleep 20")
lines.append("catch {halt}")
lines.append("sleep 20")
lines.append("catch {halt}")
lines.append("sleep 30")
lines.append("")
lines.append("# === IWDG: kick immediately to reset 273ms timer ===")
lines.append("mww 0x40003000 0x0000AAAA")
lines.append("sleep 5")
lines.append("")
lines.append("# === IWDG: extend timeout to ~17.5 seconds (PR=6=/256, RLR=4095) ===")
lines.append("# Unlock IWDG PR/RLR registers")
lines.append("mww 0x40003000 0x00005555")
lines.append("sleep 2")
lines.append("mww 0x40003004 0x00000006")
lines.append("sleep 2")
lines.append("mww 0x40003008 0x00000FFF")
lines.append("sleep 2")
lines.append("# Reload with new settings")
lines.append("mww 0x40003000 0x0000AAAA")
lines.append("sleep 5")
lines.append("puts \"IWDG extended to ~17.5s timeout\"")
lines.append("")
lines.append("# === Unlock flash ===")
lines.append("mww 0x40022004 0x45670123")
lines.append("mww 0x40022004 0xCDEF89AB")
lines.append("sleep 5")
lines.append("")
lines.append("# === Clear PGERR/WRPRTERR/EOP ===")
lines.append("mww 0x4002200C 0x00000034")
lines.append("sleep 2")
lines.append("")
lines.append("set sr [mrw 0x4002200C]")
lines.append("set cr [mrw 0x40022010]")
lines.append('puts "After unlock: SR=0x[format %08X $sr] CR=0x[format %08X $cr]"')
lines.append("")
lines.append("# === Erase pages 0-14 (512-byte pages, 0x200 stride, firmware region 0x08000000-0x08001DFF) ===")
lines.append("# N32G031 has 512-byte pages! Erase every 0x200 bytes.")
lines.append("# Kick IWDG before EVERY erase — 273ms budget must not be exceeded")
npages = (nbytes + 511) // 512   # number of 512-byte pages needed
pages = [0x08000000 + i*0x200 for i in range(npages)]
for pg in pages:
    lines.append("mww 0x40003000 0x0000AAAA")
    lines.append("puts \"Erasing page 0x{:08X}...\"".format(pg))
    lines.append("mww 0x40022014 0x{:08X}".format(pg))
    lines.append("mww 0x40022010 0x00000002")
    lines.append("mww 0x40022010 0x00000042")
    lines.append("sleep 30")
    lines.append("mww 0x40022010 0x00000000")
    lines.append("mww 0x4002200C 0x00000034")
    lines.append("")

lines.append("set sr [mrw 0x4002200C]")
lines.append('puts "After erase: SR=0x[format %08X $sr]"')
lines.append("set p0 [mrw 0x08000000]")
lines.append("set p200 [mrw 0x08000200]")
lines.append('puts "Page0: 0x[format %08X $p0] (expect 0xFFFFFFFF)"')
lines.append('puts "Page0+0x200: 0x[format %08X $p200] (expect 0xFFFFFFFF)"')
lines.append("")
lines.append("# === IWDG kick before PG writes ===")
lines.append("mww 0x40003000 0x0000AAAA")
lines.append("")
lines.append("# === PG mode: write {} words (kick IWDG every 300 words) ===".format(nwords))
lines.append("mww 0x40022010 0x00000001")
lines.append("")

for i, w in enumerate(words):
    if i % 30 == 0:
        lines.append("# IWDG kick at word {}".format(i))
        lines.append("mww 0x40003000 0x0000AAAA")
    addr = flash_base + i * 4
    lines.append("mww 0x{:08X} 0x{:08X}".format(addr, w))

lines.append("")
lines.append("sleep 5")
lines.append("mww 0x40022010 0x00000000")
lines.append("")
lines.append("set sr [mrw 0x4002200C]")
lines.append('puts "Post-write SR=0x[format %08X $sr] (expect 0x00000020 = EOP only, no PGERR)"')
lines.append("")
lines.append("# === Verify key words ===")
lines.append("set f0 [mrw 0x08000000]")
lines.append("set f200 [mrw 0x08000200]")

# What are the expected values at byte 0 and byte 0x200?
w0 = words[0]
w200_idx = 0x200 // 4
w200 = words[w200_idx] if w200_idx < len(words) else 0xFFFFFFFF
lines.append('puts "f0=0x[format %08X $f0] expect=0x{:08X}"'.format(w0))
lines.append('puts "f200=0x[format %08X $f200] expect=0x{:08X}"'.format(w200))
lines.append("")
lines.append("# === Dump for cmp verification ===")
lines.append('dump_image /tmp/flappy_direct_verify.bin 0x08000000 {}'.format(nbytes))
lines.append('puts "Dump done — run: cmp build/flappy.bin /tmp/flappy_direct_verify.bin"')
lines.append("")
lines.append("# === Boot ===")
lines.append("mww 0x40003000 0x0000AAAA")
lines.append("puts \"Booting firmware...\"")
lines.append("reset run")

with open(out_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print("Generated {} ({} lines, {} words)".format(out_path, len(lines), nwords))
print("Expected f0=0x{:08X}  f200=0x{:08X}".format(w0, w200))
