#!/usr/bin/env python3
"""Generate the build-time configuration for one or two Launcher apps."""

from __future__ import annotations

import argparse
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
GENERATED_DIR = PROJECT_DIR / "generated"
HEADER_PATH = GENERATED_DIR / "launcher_config.h"
BATCH_PATH = GENERATED_DIR / "launcher_build_config.bat"

APP_CONFIG = {
    "tetris": ("Tetris", "LAUNCHER_MODULE_TETRIS", "TETRIS"),
    "pac-man": ("Pac-Man", "LAUNCHER_MODULE_PACMAN", "PAC-MAN"),
    "pacman": ("Pac-Man", "LAUNCHER_MODULE_PACMAN", "PAC-MAN"),
    "flappy": ("Flappy", "LAUNCHER_MODULE_FLAPPY", "FLAPPY BIRD"),
    "slideshow": ("Slideshow", "LAUNCHER_MODULE_SLIDESHOW", "SLIDESHOW"),
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--apps",
        nargs="+",
        required=True,
        metavar="APP",
        help="one or two of: Tetris, Pac-Man, Flappy, Slideshow",
    )
    return parser.parse_args()


def normalize_apps(values: list[str]) -> list[tuple[str, str, str]]:
    names = [value.strip().lower() for value in values if value.strip() and value.strip().lower() != "none"]
    names = ["pac-man" if name == "pacman" else name for name in names]
    if not 1 <= len(names) <= 2:
        raise RuntimeError("Launcher requires one or two bundled apps.")
    if len(set(names)) != len(names):
        raise RuntimeError("Choose each Launcher app only once.")
    unknown = [name for name in names if name not in APP_CONFIG]
    if unknown:
        raise RuntimeError(
            f"Unknown Launcher app: {unknown[0]}. Choose Tetris, Pac-Man, Flappy, or Slideshow."
        )
    return [APP_CONFIG[name] for name in names]


def write_configuration(apps: list[tuple[str, str, str]]) -> None:
    GENERATED_DIR.mkdir(exist_ok=True)
    slots = [*apps, ("None", "LAUNCHER_MODULE_NONE", "")][:2]
    selected = {app[0] for app in apps}

    header = (
        "#ifndef GENERATED_LAUNCHER_CONFIG_H\n"
        "#define GENERATED_LAUNCHER_CONFIG_H\n\n"
        "#define LAUNCHER_MODULE_NONE       0u\n"
        "#define LAUNCHER_MODULE_TETRIS     1u\n"
        "#define LAUNCHER_MODULE_FLAPPY     2u\n"
        "#define LAUNCHER_MODULE_SLIDESHOW  3u\n"
        "#define LAUNCHER_MODULE_PACMAN     4u\n\n"
        f"#define LAUNCHER_SLOT_COUNT {len(apps)}u\n"
        f"#define LAUNCHER_SLOT_1_KIND {slots[0][1]}\n"
        f"#define LAUNCHER_SLOT_1_LABEL \"{slots[0][2]}\"\n"
        f"#define LAUNCHER_SLOT_2_KIND {slots[1][1]}\n"
        f"#define LAUNCHER_SLOT_2_LABEL \"{slots[1][2]}\"\n\n"
        f"#define LAUNCHER_HAS_TETRIS {int('Tetris' in selected)}\n"
        f"#define LAUNCHER_HAS_PACMAN {int('Pac-Man' in selected)}\n"
        f"#define LAUNCHER_HAS_FLAPPY {int('Flappy' in selected)}\n"
        f"#define LAUNCHER_HAS_SLIDESHOW {int('Slideshow' in selected)}\n\n"
        "#endif /* GENERATED_LAUNCHER_CONFIG_H */\n"
    )
    HEADER_PATH.write_text(header, encoding="ascii", newline="\n")

    batch = (
        "@rem Generated by configure_launcher.py\n"
        f"set LAUNCHER_BUILD_TETRIS={int('Tetris' in selected)}\n"
        f"set LAUNCHER_BUILD_PACMAN={int('Pac-Man' in selected)}\n"
        f"set LAUNCHER_BUILD_FLAPPY={int('Flappy' in selected)}\n"
        f"set LAUNCHER_BUILD_SLIDESHOW={int('Slideshow' in selected)}\n"
    )
    BATCH_PATH.write_text(batch, encoding="ascii", newline="\r\n")

    print("Launcher bundle: " + " + ".join(app[0] for app in apps))


def main() -> int:
    write_configuration(normalize_apps(parse_args().apps))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError) as exc:
        raise SystemExit(f"ERROR: {exc}") from exc
