#!/usr/bin/env python3
"""Generate the Launcher’s one-time factory-vape import header from JSON."""

from __future__ import annotations

import json
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parent
SEED_JSON = PROJECT_DIR / "factory_vape_level.json"
GENERATED_HEADER = PROJECT_DIR / "generated" / "vape_level_seed.h"
EMPTY_TICKS = 340_000
NO_IMPORT = 0xFFFF_FFFF


def main() -> None:
    ticks = NO_IMPORT
    source = "no factory seed file"
    if SEED_JSON.is_file():
        payload = json.loads(SEED_JSON.read_text(encoding="utf-8"))
        candidate = payload.get("factory_vape_ticks")
        if not isinstance(candidate, int) or not 0 <= candidate <= EMPTY_TICKS:
            raise SystemExit(f"{SEED_JSON} has an invalid factory_vape_ticks value.")
        ticks = candidate
        source = str(payload.get("source", "factory_vape_level.json"))

    GENERATED_HEADER.parent.mkdir(parents=True, exist_ok=True)
    GENERATED_HEADER.write_text(
        "/* Generated by make_vape_seed.py. Do not edit. */\n"
        "#ifndef LAUNCHER_VAPE_LEVEL_SEED_H\n"
        "#define LAUNCHER_VAPE_LEVEL_SEED_H\n"
        f"#define LAUNCHER_FACTORY_VAPE_TICKS {ticks}UL\n"
        "#endif /* LAUNCHER_VAPE_LEVEL_SEED_H */\n",
        encoding="utf-8",
    )
    if ticks == NO_IMPORT:
        print("No factory_vape_level.json found; Launcher starts with its saved value or full level.")
    else:
        print(f"Using factory seed: {ticks} ticks from {source}.")


if __name__ == "__main__":
    main()
